source "http://rubygems.org"

gem "actionmailer", "2.3.10"
gem "actionmailer_extensions", "0.4.3"
gem "activesupport", "2.3.10"
gem "httpclient", ">= 2.1.7"
gem "jruby-openssl", "0.7.3"
gem "json_pure"
gem "ntlm-http", ">= 0.1.3"
gem "rews", ">= 0.2.12"
gem "rfc822_util"
gem "sonar_connector"
gem "sonar_exchange_pull_connector"
gem "sonar_ews_pull_connector"
gem "sonar_imap_pull_connector"
gem "sonar_push_connector"
gem "sonar_rexchange", "0.3.8"
gem "uuidtools"

