#!/bin/bash
#
# Sonar Connector
#
# chkconfig: - 85 15
# description: start, stop, restart sonar-connector
#

# Modify the below line to point to the absolute path where the Sonar Connector has been installed to.
SONAR_CONNECTOR_HOME=/home/sonar/SonarConnector

# Set the desired log level out of [debug|info|warn|error|fatal]
LOG_LEVEL=info

RETVAL=0

case "$1" in
    start)
      god -c $SONAR_CONNECTOR_HOME/config/connector.god -P $SONAR_CONNECTOR_HOME/var/pids/god.pid -l $SONAR_CONNECTOR_HOME/log/god.log --log-level=$LOG_LEVEL
      RETVAL=$?
  ;;
    stop)
      god terminate
      RETVAL=$?
  ;;
    restart)
      god terminate
      echo "starting god..."
      god -c $SONAR_CONNECTOR_HOME/config/connector.god -P $SONAR_CONNECTOR_HOME/var/pids/god.pid -l $SONAR_CONNECTOR_HOME/log/god.log --log-level=$LOG_LEVEL
      RETVAL=$?
  ;;
    status)
      god status
      RETVAL=$?
  ;;
    *)
      echo "Usage: sonar-connector {start|stop|restart|status}"
      exit 1
  ;;
esac
 
exit $RETVAL